data_ingestion:
  bucket_name: "mlops-project2"
  bucket_file_name:
    - "anime.csv"
    - "anime_with_synopsis.csv"
    - "animelist.csv"

model:
  embedding_size: 32
  loss: mse
  optimizer: Adam
  metrics: ["mae","mse"]
  learning_rate: 0.001
  l2_reg_embedding: 0.000001 # 1e-6
  l2_reg_dense: 0.0001       # 1e-4